trigger:
  branches:
    include:
      - master  # Ou votre branche spécifique si nécessaire

schedules:
  - cron: "26 22 * * *"  # Exécution à 22:26 UTC (correspond à 01:26 UTC+3)
    displayName: "Test daily at 01:26 UTC+3"
    branches:
      include:
        - master  # Ou votre branche spécifique
    always: true  # Toujours exécuter même si aucune modification n'a été apportée

pool:
  vmImage: 'windows-latest'

steps:
  # 1. Build avec Maven et exécution des tests
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0'
      jdkArchitectureOption: 'x64'
      goals: 'clean package'

  # 2. Publier les résultats de tests JUnit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '/target/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true